import { yearsToMonths } from "../Simulation/WorldTime";

export const DEFAULT_INITIAL_POPULATION = 10;
export const MIN_INITIAL_POPULATION = 0;
export const MAX_INITIAL_POPULATION = 100;

export const WORLD_MONTH_MS = 1000;
export const NATURAL_GROWTH_CHECK_MONTHS = 6;
export const BASE_POPULATION_CAPACITY = 8;
export const TERRITORY_CELLS_PER_POPULATION = 8;
export const BASE_GROWTH_CHANCE = 0.45;

export const POPULATION_MILESTONES = [25, 50, 100, 200];
export const TERRITORY_MILESTONES = [25, 50, 75];
export const LEADER_STABLE_MONTHS = 36;
export const LEADER_MIN_GAP = 3;
export const LEADER_MIN_RATIO = 1.15;

export const SIMULATION_SPEEDS = [1, 2, 4];

export const RANDOM_EVENT_MIN_INTERVAL_MONTHS = 24;
export const RANDOM_EVENT_MAX_INTERVAL_MONTHS = 60;
export const WORLD_EFFECT_DURATION_MONTHS = 20 * 12;
export const HARVEST_GROWTH_MULTIPLIER = 1.6;
export const FAMINE_GROWTH_MULTIPLIER = 0.45;
export const HARVEST_CITY_LOYALTY_DELTA = 5;
export const FAMINE_CITY_LOYALTY_DELTA = -6;
export const POPULATION_BOOM_MIN = 3;
export const POPULATION_BOOM_MAX = 8;
export const HEAVENLY_REINFORCEMENT_COUNT = 5;
export const WEAK_FACTION_POSITIVE_EVENT_BIAS = 1.5;

export const HEGEMONY_TERRITORY_PERCENT = 75;
export const HEGEMONY_STABLE_MONTHS = 20 * 12;

export const CITY_BASE_MAX_DEFENSE = 3;
export const CITY_CAPITAL_DEFENSE_BONUS = 2;
export const CITY_DEVELOPMENT_TERRITORY_STEP = 12;
export const CITY_DEVELOPMENT_SCORE_THRESHOLDS = [0, 18, 35, 65, 100];
export const CITY_REPAIR_INTERVAL_MONTHS = 9;
export const CITY_CAPTURED_DEFENSE_RATIO = 0.35;
export const CITY_CAPTURE_GRACE_MONTHS = 3;
export const CITY_INITIAL_LOYALTY = 90;
export const CITY_FOREIGN_CAPTURE_LOYALTY = 35;
export const CITY_RECOVERED_LOYALTY = 70;
export const CITY_LOYALTY_RECOVERY_INTERVAL_MONTHS = 12;
export const CITY_MAX_STABLE_LOYALTY = 95;

export const USER_NATURAL_LOYALTY_MIN = 55;
export const USER_NATURAL_LOYALTY_MAX = 95;
export const USER_PLAYER_LOYALTY = 100;
export const USER_GOD_LOYALTY_MIN = 85;
export const USER_GOD_LOYALTY_MAX = 100;
export const USER_RESTORED_LOYALTY_MIN = 80;
export const USER_RESTORED_LOYALTY_MAX = 100;
export const EXTINCTION_REMNANT_LOYALTY = 75;
export const EXTINCTION_MID_SURRENDER_CHANCE = 0.45;
export const EXTINCTION_LOW_SURRENDER_CHANCE = 0.85;

export const REBELLION_CHECK_INTERVAL_MONTHS = 12;
export const REBELLION_LOYALTY_THRESHOLD = 28;
export const REBELLION_BASE_CHANCE = 0.18;
export const REBELLION_CITY_COOLDOWN_MONTHS = 36;
export const MAX_ACTIVE_FACTIONS = 12;
export const REBEL_LOYALTY_THRESHOLD = 18;
export const REBEL_OWNER_STABILITY_THRESHOLD = 50;
export const REBEL_INITIAL_POPULATION_MIN = 3;
export const REBEL_INITIAL_POPULATION_MAX = 6;
export const REBEL_LOW_LOYALTY_USER_THRESHOLD = 50;
export const FRONTIER_REBELLION_CHANCE = 0.04;
export const FRONTIER_EDGE_RATIO = 0.15;

export const FACTION_LABEL_REFRESH_MONTHS = 6;
export const FOCUSED_FACTION_OTHER_OPACITY = 0.32;
export const CITY_LABEL_FONT_SIZE = 13;
export const CITY_CAPITAL_LABEL_FONT_SIZE = 14;

export const FORTIFIED_ZONE_TIERS = [
  { minDefense: 1, maxDefense: 4, shape: "single", maxCells: 1 },
  { minDefense: 5, maxDefense: 6, shape: "cross", maxCells: 5 },
  { minDefense: 7, maxDefense: 8, shape: "square", maxCells: 9 },
  { minDefense: 9, maxDefense: 99, shape: "diamond", maxCells: 13 },
] as const;

export const CITY_SIEGE_DAMAGE_INTERVAL_MONTHS = 2;
export const CITY_SIEGE_DAMAGE_PER_TICK = 1;

export const FACTION_SNAPSHOT_INTERVAL_MONTHS = 12;
export const FACTION_SNAPSHOT_MAX_LENGTH = 500;

export const RULER_MIN_REIGN_YEARS = 20;
export const RULER_MAX_REIGN_YEARS = 45;
export const RULER_MIN_AGE_AT_ACCESSION = 18;
export const RULER_MAX_AGE_AT_ACCESSION = 42;
export const RULER_COMBAT_MIN_AGE = 16;
// Age of a linked parent when an heir is born; distinct from accession age.
export const HEIR_PARENT_MIN_AGE_AT_BIRTH = 18;
export const HEIR_PARENT_MAX_AGE_AT_BIRTH = 40;
export const SUCCESSION_LOOKBACK_YEARS = 10;
export const SUCCESSION_LONG_REIGN_YEARS = 30;
export const SUCCESSION_SHOCK_YEARS = 8;
export const SUCCESSION_LONG_REIGN_SHOCK_YEARS = 12;
export const SUCCESSION_SHOCK_LOYALTY_MULTIPLIER = 0.8;
export const SUCCESSION_SHOCK_REBELLION_MULTIPLIER = 1.15;
export const SUCCESSION_INSTABILITY_LOYALTY_MULTIPLIER = 0.65;
export const SUCCESSION_INSTABILITY_REBELLION_MULTIPLIER = 1.25;
export const SUCCESSION_CRISIS_LOYALTY_MULTIPLIER = 0.45;
export const SUCCESSION_CRISIS_REBELLION_MULTIPLIER = 1.55;

export const RULER_ESCAPE_BASE_CHANCE = 0.72;
export const RULER_CAPTURE_EXECUTION_CHANCE = 0.72;
export const RULER_ACCESSION_BATTLE_GRACE_MONTHS = 18;
export const RULER_BATTLE_DEATH_CHAIN_COOLDOWN_MONTHS = 24;
export const RULER_TAG_EXPANSION_TERRITORY_DELTA = 0.1;
export const RULER_TAG_DECLINE_TERRITORY_DELTA = -0.08;
export const RULER_TAG_STEWARD_MIN_REIGN_MONTHS = yearsToMonths(25);
export const RULER_TAG_SHORT_REIGN_MONTHS = yearsToMonths(5);
export const RULER_TAG_CONQUEROR_CAPTURE_COUNT = 2;
export const EXILE_INITIAL_LEGITIMACY_MIN = 70;
export const EXILE_INITIAL_LEGITIMACY_MAX = 90;
export const EXILE_LEGITIMACY_DECAY_INTERVAL_MONTHS = 12;
export const EXILE_REMNANT_DECAY_INTERVAL_MONTHS = 18;
export const EXILE_BASE_LEGITIMACY_DECAY = 4;
export const EXILE_REMNANT_DECAY_CHANCE = 0.45;

export const IMPERIAL_STRAIN_TERRITORY_START = 45;
export const IMPERIAL_STRAIN_TERRITORY_HIGH = 65;
export const IMPERIAL_STRAIN_CITY_START = 4;
export const IMPERIAL_STRAIN_CITY_HIGH = 6;
export const IMPERIAL_STRAIN_UNIFIED_MONTH_FACTOR = 0.08;
export const IMPERIAL_STRAIN_DISTANCE_FACTOR = 0.9;
export const IMPERIAL_STRAIN_LOYALTY_DECAY_THRESHOLD = 70;

export const EMPIRE_SPLIT_CHECK_INTERVAL_MONTHS = 12;
export const EMPIRE_SPLIT_MIN_CITIES = 4;
export const EMPIRE_SPLIT_STABILITY_THRESHOLD = 45;
export const EMPIRE_SPLIT_STRAIN_THRESHOLD = 72;
export const EMPIRE_SPLIT_LOW_LOYALTY = 42;
export const EMPIRE_SPLIT_MAX_CITIES = 3;

export const CITY_CAPTURE_DEVASTATION = 12;
export const CITY_REPEAT_CAPTURE_WINDOW_MONTHS = 120;
export const CITY_REPEAT_CAPTURE_DEVASTATION = 10;
export const CITY_SIEGE_DEVASTATION_INTERVAL_MONTHS = 24;
export const CITY_SIEGE_DEVASTATION = 4;
export const CITY_DEVASTATION_RECOVERY_INTERVAL_MONTHS = 12;
export const CITY_DEVASTATION_RECOVERY = 1;
export const CITY_DESTRUCTION_THRESHOLD = 100;
export const MIN_ACTIVE_CITIES = 5;
export const MAX_ACTIVE_CITIES = 16;

export const CITY_FOUND_CHECK_INTERVAL_MONTHS = 24;
export const CITY_FOUND_MIN_TERRITORY = 90;
export const CITY_FOUND_MIN_POPULATION = 18;
export const CITY_FOUND_MIN_STABILITY = 60;
export const CITY_FOUND_MIN_DISTANCE_CELLS = 8;
export const CITY_MIN_ZONE_GAP = 1;
export const CITY_FOUND_COOLDOWN_MONTHS = 240;

export const REBEL_LOYALTY_THRESHOLD_V095 = 26;
export const REBEL_OWNER_STABILITY_THRESHOLD_V095 = 55;

export const WORLD_YEAR_MS = WORLD_MONTH_MS;
export const NATURAL_GROWTH_CHECK_YEARS = NATURAL_GROWTH_CHECK_MONTHS;
export const LEADER_STABLE_YEARS = LEADER_STABLE_MONTHS;
export const RANDOM_EVENT_MIN_INTERVAL_YEARS = RANDOM_EVENT_MIN_INTERVAL_MONTHS;
export const RANDOM_EVENT_MAX_INTERVAL_YEARS = RANDOM_EVENT_MAX_INTERVAL_MONTHS;
export const WORLD_EFFECT_DURATION_YEARS = WORLD_EFFECT_DURATION_MONTHS;
export const HEGEMONY_STABLE_YEARS = HEGEMONY_STABLE_MONTHS;
export const CITY_REPAIR_INTERVAL_YEARS = CITY_REPAIR_INTERVAL_MONTHS;
export const CITY_CAPTURE_GRACE_YEARS = CITY_CAPTURE_GRACE_MONTHS;
export const CITY_LOYALTY_RECOVERY_INTERVAL_YEARS = CITY_LOYALTY_RECOVERY_INTERVAL_MONTHS;
export const REBELLION_CHECK_INTERVAL_YEARS = REBELLION_CHECK_INTERVAL_MONTHS;
export const REBELLION_CITY_COOLDOWN_YEARS = REBELLION_CITY_COOLDOWN_MONTHS;
export const FACTION_LABEL_REFRESH_YEARS = FACTION_LABEL_REFRESH_MONTHS;
export const CITY_SIEGE_DAMAGE_INTERVAL_YEARS = CITY_SIEGE_DAMAGE_INTERVAL_MONTHS;
export const FACTION_SNAPSHOT_INTERVAL_YEARS = FACTION_SNAPSHOT_INTERVAL_MONTHS;

export const RULER_MIN_REIGN_MONTHS = yearsToMonths(RULER_MIN_REIGN_YEARS);
export const RULER_MAX_REIGN_MONTHS = yearsToMonths(RULER_MAX_REIGN_YEARS);
export const SUCCESSION_LOOKBACK_MONTHS = yearsToMonths(SUCCESSION_LOOKBACK_YEARS);
export const SUCCESSION_LONG_REIGN_MONTHS = yearsToMonths(SUCCESSION_LONG_REIGN_YEARS);
export const SUCCESSION_SHOCK_MONTHS = yearsToMonths(SUCCESSION_SHOCK_YEARS);
export const SUCCESSION_LONG_REIGN_SHOCK_MONTHS = yearsToMonths(
  SUCCESSION_LONG_REIGN_SHOCK_YEARS
);
